name: 🐛 Bug Report
description: Report something that's broken
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve! Please describe the issue clearly.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: "When I click X, Y happens instead of Z"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: "I expected Z to happen"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Device
      placeholder: "e.g., Chrome 120 on macOS, Safari on iPhone 15"

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If helpful, drag and drop a screenshot here
